name: Build and Store Artifact

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or whatever your version is

      - name: Install dependencies
        run: npm install

      - name: Run Build (optional)
        run: npm run build || echo "No build script defined"

      - name: Create zip artifact
        run: |
          mkdir -p output
          zip -r output/fake-product-identification.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-package
          path: output/fake-product-identification.zip
