name: Build and Deploy

# This workflow triggers on any push or pull request to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Use GitHub secret in build step
      - name: Use Secret in Build
        run: |
              echo "Using secret in build step..."
                echo "First 4 characters of secret: ${MY_SECRET:0:4}"
        env:
            MY_SECRET: ${{ secrets.MY_SECRET }}
    
      # Step 5: Build the project (optional)
      - name: Run Build (optional)
        run: npm run build || echo "No build script defined"

      # Step 6: Package project and store as artifact
      - name: Create zip artifact
        run: |
          mkdir -p output
          zip -r output/fake-product-identification.zip .

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: project-package
          path: output/fake-product-identification.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 7: Checkout code again for deploy
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 8: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 9: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 10: Build
